### ISSUE TITLE
VirusTotal marks this as a virus on many Antiviruses and Norton marked this as dangerous.

### ISSUE THREAD

**Issue by tiredsoot** [Jonius7/SteamUI-OldGlory#58]
Aforementioned VirusTotal marks:
![image](https://user-images.githubusercontent.com/108702530/187009403-1b87932f-8839-4b03-a7ce-d8b84434c6cf.png)
and the Norton mark:
![image](https://user-images.githubusercontent.com/108702530/187009439-05b6831c-31b8-4924-b2da-a4c4d0986c88.png)

Is this actually dangerous? This may be a stupid question but I need a serious answer please...

Thank you in advance.

Update: Confusingly, Norton (with a full scan) found no threats. So weird...

**Comment by Jonius7** [comment]
OldGlory is safe but certain versions have been flagged as a false positive in the past. This is due to the exe being built by Pyinstaller

Here's an example of a Pyinstaller false positive: https://github.com/pyinstaller/pyinstaller/issues/6754

You can see the VirusTotal for version 5.9 here: https://www.virustotal.com/gui/file/be0aa6a7c3d54b9d76b6533b73f47f98ca15703c39b2674bfe6fce3f967da143?nocache=1

**Comment by tiredsoot** [comment]
Okay, thank you.
