### ISSUE TITLE
entire steam window does not change correctly

### ISSUE THREAD

**Issue by captinwill** [Jonius7/SteamUI-OldGlory#97]
![Screenshot (15)](https://github.com/Jonius7/SteamUI-OldGlory/assets/71353277/83f0f1d0-b383-4e19-92da-333ef41e6156)

**Comment by Jonius7** [comment]
This is due to the new version of Steam changing the top bar and "supernav"

As I did not develop the OG-Steam theme it requires separate updating from either the original developer (ungstein), or I'll have a look at it, but no guarantees.

For now you can still access the old Steam Skins via `-vgui` and download the old skin here: https://github.com/ungstein/OG-Steam

**Comment by Bodyawad93** [comment]
> This is due to the new version of Steam changing the top bar and "supernav"
> 
> As I did not develop the OG-Steam theme it requires separate updating from either the original developer (ungstein), or I'll have a look at it, but no guarantees.
> 
> For now you can still access the old Steam Skins via `-vgui` and download the old skin here: https://github.com/ungstein/OG-Steam

well i have the issue EVEN when i  dont have a theme equipped so pls fix

**Comment by BuzzfeedBlue** [comment]
-vgui does nothing for me as of 9.12.23

**Comment by Jonius7** [comment]
Fixed as of b1a95ab178e2e83f85cbb186243812acb4a31daf
